zoey_Prep javascript objects
Zoey1318/prep-0722-code-solutions pull request #11
Opened 2022-08-19 06:42 UTC by Zoey1318

![javascript-objects_Screenshot 2022-08-18 233604](https://user-images.githubusercontent.com/111097580/185559160-02a01f63-3667-4124-a7a9-87e1b099d35c.jpg)

2022-08-19 14:24 UTC, thebearingedge requested changes

2022-08-19 14:24 UTC, thebearingedge commented on prep-javascript-objects/main.js
> +console.log('FullName:', fullName);
Hi Zoey, you can get the full name of the person with dot notation.

```js
var fullName = person.firstName + ' ' + person.lastName;
```

2022-08-20 02:19 UTC, Zoey1318 commented on prep-javascript-objects/main.js
> +console.log('FullName:', fullName);
Hi Tim, revised the code as advised!
![resubmit_javascript-objects_Screenshot 2022-08-19 190904](https://user-images.githubusercontent.com/111097580/185725469-f5943970-8483-4893-9ccb-63a082537d9c.jpg)

2022-08-20 02:32 UTC, thebearingedge approved these changes

2022-08-20 03:19 UTC, merged